[package]
name = "selenite-lamp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = "3.0.0-beta.4"
serialport = "4.0.1"
serde = { version = "1.0", features = ["derive"] }
termios = "0.3.3"
